name: Diff

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          mv test test.old
          # replace workd in test file with another word
          sed 's/green/orange/g' test.old > test
          diff -u --color=always test test.old  && echo $? || true
 
